sudo: required

dist: xenial

language: java

addons:
    apt:
        packages:
            - ant
            - ant-optional
            - unzip
            - wget
            - make
            - openjdk-8-jdk
            - subversion

script:
    - jdk_switcher use openjdk8
    - javac -version
    - java -version
    - make --version
    - make audit
