sudo: required

dist: xenial

language: java

jdk:
  - openjdk8

addons:
    apt:
        packages:
            - ant
            - ant-optional
            - unzip
            - wget
            - make
            - openjdk-8-jdk
            - subversion

script:
    - javac -version
    - java -version
    - make --version
    - make audit
