sudo: required

dist: xenial

addons:
    apt:
        packages:
            - ant
            - ant-optional
            - unzip
            - wget
            - make
            - openjdk-8-jdk
            - subversion

script:
    - javac -version
    - make --version
    - make audit
