sudo: required

dist: trusty
language: perl

addons:
    apt:
        packages:
            - ant
            - unzip
            - default-jdk
            - subversion

# Skip cpanm installation
install: []

script:
    - make --version
    - make 2>&1 | tee make.log && if grep FAILED make.log; then exit 123; fi
