sudo: required

dist: trusty
language: perl

addons:
    apt:
        packages:
            - unzip
            - default-jdk

# Skip cpanm installation
install: []

script:
    - make tests 2>&1 | tee make.log && if grep FAILED make.log; then exit 123; fi
